name: "Tests"
on: ["push"]

jobs:
  ci:
    name: "Run CI"
    strategy:
      fail-fast: false
      matrix:
        os:  ["ubuntu-latest", "macOS-latest"]
        go:  ["1.23.x"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version: ${{ matrix.go }}
      - run: "go test ./..."
      - run: "go vet ./..."
      - uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"
          install-go: false
          cache-key: ${{ matrix.go }}
          working-directory: ${{ matrix.dir }}